apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: uds-package-app
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.sso }}
  sso:
    - name: SSO
      clientId: uds-core-uds-package-app
      redirectUris:
        - "https://hostname-for-uds-package.{{ .Values.domain }}/users/auth/openid_connect/callback"
  {{- end }}
  network:
    expose:
      - service: uds-package-app
        podLabels:
          app.kubernetes.io/name: uds-package-app
        host: hostname-for-uds-package
        gateway: tenant
        port: 9898

    allow:
      - direction: Ingress
        remoteGenerated: IntraNamespace

      - direction: Ingress
        remoteNamespace: monitoring
        remotePodLabels:
          app: prometheus
        podLabels:
          app.kubernetes.io/name: uds-package-app
        port: 15021
        description: "Monitoring"

